### ISSUE TITLE
Fair Use License? 

### ISSUE THREAD

**Issue by OUStudent** [3outeille/CNNumpy#1]
I've been trying to contact the owner, 3outeille, but no email was given in your profile so I'm going to leave my question here. 

I'm currently working on a non-commercial Python library covering Evolutionary Computation, where one of my modules covers Reinforcement Learning through using genetic algorithms on a population of neural networks. I want to extend it to handle images by evolving CNN layers, as it only works through a dense layer. 

Do I have your permission to use your CNNumpy scripts in my library? Proper recognition and citation will be followed of course.

**Comment by 3outeille** [comment]
Sure you can use it !
